name: Bug Report
description: Create a bug report
labels: []
body:
    - type: textarea
      attributes:
          label: Describe the Bug
          description: A clear and concise description of what the bug is.
      validations:
          required: true

    - type: textarea
      attributes:
          label: Environment
          description: Please fill out the relevant details below for your environment.
          value: |
              - OS Type & Version: (e.g., Ubuntu 22.04)
              - Pangolin Version:
              - Gerbil Version:
              - Traefik Version:
              - Newt Version:
              - Olm Version: (if applicable)
      validations:
          required: true

    - type: textarea
      attributes:
          label: To Reproduce
          description: |
              Steps to reproduce the behavior, please provide a clear description of how to reproduce the issue, based on the linked minimal reproduction. Screenshots can be provided in the issue body below.

              If using code blocks, make sure syntax highlighting is correct and double-check that the rendered preview is not broken.
      validations:
          required: true

    - type: textarea
      attributes:
          label: Expected Behavior
          description: A clear and concise description of what you expected to happen.
      validations:
          required: true

    - type: markdown
      attributes:
          value: |
              Before posting the issue go through the steps you've written down to make sure the steps provided are detailed and clear.

    - type: markdown
      attributes:
          value: |
              Contributors should be able to follow the steps provided in order to reproduce the bug.
